# Generated by Django 5.2.1 on 2025-05-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MixModelRequests',
            fields=[
                ('orderName', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='PENDING', max_length=10)),
                ('solicitor', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('statusColor', models.CharField(choices=[('#FFDE21', 'yellow'), ('#FF3F41', 'red'), ('#56D47A', 'green')], default='#FFDE21', max_length=7)),
            ],
        ),
    ]
