# Generated by Django 5.2.1 on 2025-05-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mixmodelrequests',
            name='statusColor',
        ),
        migrations.AlterField(
            model_name='mixmodelrequests',
            name='status',
            field=models.CharField(choices=[('PND', 'Pending'), ('ACC', 'Accepted'), ('REJ', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
