# Generated by Django 5.2.1 on 2025-05-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_mixmodelrequests_statuscolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixmodelrequests',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
