# Generated by Django 5.2.1 on 2025-05-18 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_mixmodelrequests_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MixModelRequests',
            new_name='MixModelRequest',
        ),
    ]
